name: Bug Report
description: "Report something that's broken"
body:
  - type: markdown
    attributes:
      value: |
        Before creating a new bug report, please check that there isn't already a similar issue.

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Steps To Reproduce"
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1. 
        2. 
        3. 
    validations:
      required: false

  - type: input
    attributes:
      label: System Info
      description: Provide any system details relevant to the issue
      placeholder: "Device, operating system, browser, etc."
    validations:
      required: false
