name: ci

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: Testing
    strategy:
      fail-fast: true
      matrix:
        php-version: ['8.5']
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: xdebug

      - name: Lint PHP Files
        run: find app bootstrap config database routes -name "*.php" -print0 | xargs -0 -P4 php -l

      - uses: oven-sh/setup-bun@v2

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: 'bun'

      - name: Cache Node Modules
        id: node-modules-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/bun.lock') }}

      - name: Install Node Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: bun install

      - name: Add Flux Credentials Loaded From ENV
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Cache Vendor
        id: vendor-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}

      - name: Install Dependencies
        if: steps.vendor-cache.outputs.cache-hit != 'true'
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader

      - name: Audit Dependencies
        run: composer audit --no-interaction --ansi

      - name: Build Assets
        run: |
          bun run build
          node bin/build.ts

      - name: Prepare Application
        run: |
          php artisan config:clear
          cp .env.example .env
          php artisan key:generate
          php artisan storage:link
          mkdir -p storage/framework/cache/data
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          mkdir -p bootstrap/cache

      - name: Create Workspace Archive
        run: |
          tar --exclude='./.git' -zcf ../workspace.tar.gz .
          mv ../workspace.tar.gz ./workspace.tar.gz

      - name: Upload Workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: workspace.tar.gz
          retention-days: 1

  php-tests:
    runs-on: ubuntu-latest
    environment: Testing
    needs: setup
    strategy:
      fail-fast: true
      matrix:
        php-version: ['8.5']
        shard: [1, 2]
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Extract Workspace
        run: |
          tar xzf workspace.tar.gz
          rm workspace.tar.gz

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: bunx playwright install --with-deps

      - name: Install Playwright System Dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: bunx playwright install-deps

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: xdebug

      - name: Run Tests
        run: ./vendor/bin/pest --parallel --coverage --cache-directory=storage/app/pest --shard ${{ matrix.shard }}/2 --ci

      - name: Store Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: browser-screenshots
          path: tests/Browser/Screenshots

  js-tests:
    runs-on: ubuntu-latest
    environment: Testing
    needs: setup
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Extract Workspace
        run: |
          tar xzf workspace.tar.gz
          rm workspace.tar.gz

      - uses: oven-sh/setup-bun@v2

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: 'bun'

      - name: Run Javascript Tests
        run: bun run test
        env:
          LARAVEL_BYPASS_ENV_CHECK: 1

  static-analysis:
    runs-on: ubuntu-latest
    environment: Testing
    needs: setup
    strategy:
      fail-fast: true
      matrix:
        php-version: ['8.5']
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Extract Workspace
        run: |
          tar xzf workspace.tar.gz
          rm workspace.tar.gz

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: Cache PHPStan
        uses: actions/cache@v4
        with:
          path: ./storage/phpstan
          key: ${{ runner.os }}-phpstan-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-phpstan-

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --error-format=github --no-progress

  code-style-fixes:
    runs-on: ubuntu-latest
    environment: Testing
    needs: setup
    strategy:
      fail-fast: true
      matrix:
        php-version: ['8.5']
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Extract Workspace
        run: |
          tar xzf workspace.tar.gz
          rm workspace.tar.gz

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - uses: oven-sh/setup-bun@v2

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: 'bun'

      - name: Cache Rector
        uses: actions/cache@v4
        with:
          path: ./storage/rector/cache
          key: ${{ runner.os }}-rector-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-rector-

      - name: Cache Pint
        uses: actions/cache@v4
        with:
          path: ./storage/pint.cache
          key: ${{ runner.os }}-pint-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-pint-

      - name: Run Rector
        run: vendor/bin/rector --ansi

      - name: Run Pint
        run: vendor/bin/pint

      - name: Run ESLint Fix
        run: bun run lint

      - name: Run Prettier
        run: bun run format

      - name: Normalize Composer
        run: composer normalize --ansi --no-interaction

      - name: Checkout
        uses: actions/checkout@v6

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Fix code style
          commit_options: '--no-verify'
          file_pattern: |
            **/*
            !.github/workflows/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
